{% set name = "act" %}
{% set version = "0.97" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - path: ../..
    folder: ACT
  - git_url: https://github.com/dspoel/openbabel.git
    folder: openbabel

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - openmpi  # [linux]  
    - llvm-openmp  # [osx]
    - boost
    - git
    - make
    - graphviz
    - cmake=3
    - cairo
    - fftw
    - eigen
    - bzip2
    - zlib
    - libxml2
    - swig
    - sqlite
    - doxygen
  host:
    - python
  run:
    - libgcc-ng= # [linux]
    - boost
    - openmpi # [linux]  
    - llvm-openmp  # [osx]
    - matplotlib
    - pubchempy
    - numpy
    - cairo
    - graphviz
    - fftw
    - eigen
    - zlib
    - libxml2
    - swig
    - sqlite
    - doxygen
  run_constrained:
    - python>=3.10

about:
  home: https://github.com/AlexandriaChemistry/ACT
  license: GPLv2
  summary: 'Global optimization of force fields for molecular simulation'
  doc_url: https://doi.org/10.5281/zenodo.15020365
